//! `octans-codegen` — lower a graph's IR ([`GraphSpec`]) to **Rust source**.
//!
//! This is the first rung of the AOT (`Canopus`) path: instead of loading a spec at runtime,
//! emit a `build()` function with the graph's structure baked in — every node construction and
//! connection as explicit Rust. The generated function still constructs nodes via the runtime
//! [`NodeRegistry`](octans_core::NodeRegistry) (so node *logic* isn't inlined yet — that deeper
//! rung needs per-node code templates and a compile step). What we have is the IR → valid-Rust
//! lowering, verifiable by parsing the output.

use octans_core::GraphSpec;

/// Emit a Rust `build(registry, factories) -> Result<Graph, BuildError>` function whose body
/// reconstructs `spec`'s graph with its structure unrolled into explicit statements.
pub fn emit_rust(spec: &GraphSpec) -> String {
    let mut s = String::new();
    s.push_str("// @generated by octans-codegen — do not edit.\n");
    s.push_str("pub fn build(\n");
    s.push_str("    registry: ::octans_core::Registry,\n");
    s.push_str("    factories: &::octans_core::NodeRegistry,\n");
    s.push_str(") -> ::core::result::Result<::octans_core::Graph, ::octans_core::BuildError> {\n");
    s.push_str("    use ::octans_core::NodeId;\n");
    s.push_str("    let mut g = ::octans_core::Graph::new(registry);\n");

    for (i, n) in spec.nodes.iter().enumerate() {
        let cfg = serde_json::to_string(&n.config).unwrap_or_else(|_| "null".to_string());
        s.push_str(&format!(
            "    let n{i} = g.add_boxed(\n        factories\n            .build({:?}, &::serde_json::from_str({:?}).unwrap())\n            .ok_or_else(|| ::octans_core::BuildError::UnknownNodeType({:?}.to_string()))?,\n    );\n",
            n.type_id, cfg, n.type_id
        ));
    }

    for e in &spec.edges {
        s.push_str(&format!(
            "    g.connect(n{}, {:?}, n{}, {:?}).map_err(::octans_core::BuildError::Connect)?;\n",
            e.from, e.from_port, e.to, e.to_port
        ));
    }

    s.push_str("    Ok(g)\n}\n");
    s
}
